openapi: "3.0.2"
info:
  version: 1.0.0
  title: Commons
  license:
    name: Afone
paths: {}
components:
  responses:
    '204':
      description: No content
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - Token: [ ]
