openapi: 3.0.2
info:
  version: 1.0.0
  title: Errors API
  license:
    name: Afone
    
paths: {}

components:
  responses:
    '400':
      description: Failed request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDto'
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDto'
    '403':
      description: Authorization incorrect
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDto'
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDto'
    '500':
      description: Failed request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDto'
  schemas:
    ErrorDto:
      title: Error 
      type: object
      required: 
        - date
        - status
        - errorCode
        - message
      properties:
        date:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - ZERO_RESULTS
            - REQUEST_DENIED
            - INVALID_REQUEST
            - UNKNOWN_ERROR
        errorCode:
          $ref: '#/components/schemas/ErrorCodeDto'
        message:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/ErrorFieldDto'

    ErrorFieldDto:
      title: ErrorField
      type: object
      properties:
        field:
          type: string
        value:
          type: string
  
    ErrorCodeDto:
      title: ErrorCode
      type: string
      enum:
        - C000
        - C100
        - C999
      description: >
        errorCode:
          * `C000` - Invalid parameters
          * `C100` - Element not found
          * `C999` - Internal exception